[options]
addons_path = C:\Project\odoo18\odoo\addons,C:\Project\odoo18\odoo18_demo_ERP\
admin_passwd = admin123

db_host = localhost
db_port = 5432
db_user = odoo
db_password = 1234
db_name = odoo18_demoerp

logfile = C:\Project\odoo18\odoo18_demo_ERP\odoo18demo.log
http_port = 9901
proxy_mode = False

limit_memory_soft = 268435456
limit_memory_hard = 536870912
limit_time_cpu = 60
limit_time_real = 120
workers = 0



# python C:\Project\odoo18\odoo\odoo-bin -c odoo.conf

# python C:\Project\odoo18\odoo\odoo-bin -c odoo.conf -d odoo18_demoerp -i base

# python C:\Project\odoo18\odoo\odoo-bin -c C:\Project\odoo18\odoo18_demo_ERP\odoo.conf

